spring.application.name=gb

jwt.secret=gamebox-api-secret-key-2026-super-safe

app.upload-dir=uploads
app.base-url=http://localhost:8080

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console